export const SET_REGISTER_EMAIL = 'SET_REGISTER_EMAIL';
export const SET_REGISTER_FIRST_NAME = 'SET_REGISTER_FIRST_NAME';
export const SET_REGISTER_LAST_NAME = 'SET_REGISTER_LAST_NAME';
export const SET_REGISTER_PASSWORD = 'SET_REGISTER_PASSWORD';
export const SET_REGISTER_PASSWORD_CONFIRM = 'SET_REGISTER_PASSWORD_CONFIRM';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
